---
global:
  scrape_interval: 3s
  evaluation_interval: 3s


scrape_configs:
- job_name: 'quarkus'
  metrics_path: '/q/metrics/'
  static_configs:
  - targets: ['docker.for.mac.host.internal:9001', 'docker.for.mac.host.internal:9002']
- job_name: 'kafka'
  metrics_path: "/metrics"
  static_configs:
    - targets: ['docker.for.mac.host.internal:8081']
